apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.application.name }}
  namespace: {{.Values.global.namespace}}
  labels:
    app: {{ .Values.global.application.name }}
    stack: springboot
    {{- with .Values.global.application.annotations}}
  annotations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.application.port }}
  selector:
    app: {{ .Values.global.application.name }}
